version: "3.6"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  # certs-volume:

services:
  nginx:
    image: nginx:alpine
    # build:
    #   context: .
    #   dockerfile: compose/nginx/Dockerfile
    container_name: nz01
    # env_file:
    #   - ./.envs/.nginx
    ports:
      - "8000:8000"
      # - "443:443"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      # - certs-volume:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - djangonetwork
  web:
    restart: always
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: dz01
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis
    env_file:
      - ./.envs/.django
    networks:
      - djangonetwork
  db:
    image: postgres:10
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    container_name: pz01
    env_file:
      - ./.envs/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    networks:
      - djangonetwork
  redis:
    image: "redis"
    container_name: rz01
    ports:
      - "6379:6379"
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
