# Generated by Django 2.2.1 on 2020-06-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoModel',
        ),
    ]
