# Generated by Django 2.2.1 on 2020-05-16 07:13

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
                ('slug', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('parent_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('number_of_page', models.IntegerField(default=0)),
                ('number_of_view', models.IntegerField(default=0)),
                ('number_of_download', models.IntegerField(default=0)),
                ('size_of_file', models.FloatField(default=0.0)),
                ('doc_file', models.FileField(null=True, upload_to='doc/%Y/%m/%d/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='demo_images')),
                ('video_url', models.CharField(max_length=255)),
                ('file_field', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.SubCategory')),
                ('tags', models.ManyToManyField(to='documents.Tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
