# Generated by Django 2.2.1 on 2020-06-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Danh Mục Nhỏ'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Thẻ'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent_cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentCategory', verbose_name='Nhóm Tài Liệu'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Hạng Mục'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_title',
            field=models.CharField(max_length=255, verbose_name='Tiêu Đề Nhỏ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=250, verbose_name='Hạng Mục'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.CharField(max_length=35, verbose_name='Từ Khóa Thẻ'),
        ),
    ]
